# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{saucelabs-adapter}
  s.version = "0.9.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kelly Felkins, Chad Woolley, Sam Pierson, Nate Clark"]
  s.date = %q{2011-01-20}
  s.description = %q{This gem augments Test::Unit and Polonium/Webrat to run Selenium tests in the cloud. }
  s.email = %q{pair+kelly+sam@pivotallabs.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.markdown"
  ]
  s.files = [
    "LICENSE",
    "Rakefile",
    "VERSION",
    "generators/saucelabs_adapter/saucelabs_adapter_generator.rb",
    "generators/saucelabs_adapter/templates/jsunit.rake",
    "generators/saucelabs_adapter/templates/jsunit_suite_example.rb",
    "generators/saucelabs_adapter/templates/sample_webrat_test.rb",
    "generators/saucelabs_adapter/templates/saucelabs_adapter.rake",
    "generators/saucelabs_adapter/templates/selenium.yml",
    "generators/saucelabs_adapter/templates/selenium_suite.rb",
    "lib/saucelabs-adapter.rb",
    "lib/saucelabs_adapter.rb",
    "lib/saucelabs_adapter/jsunit_selenium_support.rb",
    "lib/saucelabs_adapter/rspec_adapter.rb",
    "lib/saucelabs_adapter/run_utils.rb",
    "lib/saucelabs_adapter/selenium_config.rb",
    "lib/saucelabs_adapter/test_unit_adapter.rb",
    "lib/saucelabs_adapter/tunnel.rb",
    "lib/saucelabs_adapter/tunnels/other_tunnel.rb",
    "lib/saucelabs_adapter/tunnels/sauce_connect_tunnel.rb",
    "lib/saucelabs_adapter/tunnels/sauce_tunnel.rb",
    "lib/saucelabs_adapter/tunnels/ssh_tunnel.rb",
    "lib/saucelabs_adapter/utilities.rb",
    "lib/saucerest-ruby/README.md",
    "lib/saucerest-ruby/gateway.rb",
    "lib/saucerest-ruby/listtunnels.rb",
    "lib/saucerest-ruby/saucerest.rb",
    "lib/saucerest-ruby/tunnel.rb"
  ]
  s.homepage = %q{http://github.com/pivotal/saucelabs-adapter}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Adapter for running Selenium tests using SauceLabs.com}
  s.test_files = [
    "spec/selenium_config_spec.rb",
    "spec/spec_helper.rb",
    "test/helper.rb",
    "test/test_saucelabs-adapter.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 2.3.0"])
      s.add_runtime_dependency(%q<sauce>, [">= 0.12.9"])
      s.add_development_dependency(%q<rspec>, ["= 1.3.0"])
      s.add_development_dependency(%q<rake>, ["= 0.8.7"])
      s.add_development_dependency(%q<json>, [">= 1.4.3"])
      s.add_development_dependency(%q<jeweler>, ["= 1.5.2"])
      s.add_runtime_dependency(%q<rest-client>, [">= 1.5.0"])
      s.add_runtime_dependency(%q<net-ssh>, [">= 2.0.12"])
      s.add_runtime_dependency(%q<net-ssh-gateway>, [">= 1.0.1"])
      s.add_runtime_dependency(%q<selenium-client>, [">= 1.2.17"])
      s.add_runtime_dependency(%q<lsof>, [">= 0.3.0"])
      s.add_runtime_dependency(%q<sauce>, [">= 0.12.9"])
    else
      s.add_dependency(%q<activesupport>, [">= 2.3.0"])
      s.add_dependency(%q<sauce>, [">= 0.12.9"])
      s.add_dependency(%q<rspec>, ["= 1.3.0"])
      s.add_dependency(%q<rake>, ["= 0.8.7"])
      s.add_dependency(%q<json>, [">= 1.4.3"])
      s.add_dependency(%q<jeweler>, ["= 1.5.2"])
      s.add_dependency(%q<rest-client>, [">= 1.5.0"])
      s.add_dependency(%q<net-ssh>, [">= 2.0.12"])
      s.add_dependency(%q<net-ssh-gateway>, [">= 1.0.1"])
      s.add_dependency(%q<selenium-client>, [">= 1.2.17"])
      s.add_dependency(%q<lsof>, [">= 0.3.0"])
      s.add_dependency(%q<sauce>, [">= 0.12.9"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 2.3.0"])
    s.add_dependency(%q<sauce>, [">= 0.12.9"])
    s.add_dependency(%q<rspec>, ["= 1.3.0"])
    s.add_dependency(%q<rake>, ["= 0.8.7"])
    s.add_dependency(%q<json>, [">= 1.4.3"])
    s.add_dependency(%q<jeweler>, ["= 1.5.2"])
    s.add_dependency(%q<rest-client>, [">= 1.5.0"])
    s.add_dependency(%q<net-ssh>, [">= 2.0.12"])
    s.add_dependency(%q<net-ssh-gateway>, [">= 1.0.1"])
    s.add_dependency(%q<selenium-client>, [">= 1.2.17"])
    s.add_dependency(%q<lsof>, [">= 0.3.0"])
    s.add_dependency(%q<sauce>, [">= 0.12.9"])
  end
end

